### ISSUE TITLE
generate event id if not exists. 

### ISSUE THREAD

**Issue by hasithadkr7** [shadhini/curw_db_adapter#1]
https://github.com/shadhini/curw_db_adapter/blob/200070a66ece6fc2a63ab4b04ea373cf7ca07a83/db_adapter/timeseries/timeseries.py#L63

**Comment by shadhini** [comment]
[`def get_timeseries_id(self, meta_data):` 
](https://github.com/shadhini/curw_db_adapter/blob/367b6d8742fbc6902ee9bcab50946ede212c4ad2/db_adapter/curw_fcst/timeseries/timeseries.py#L56)
Above method is used to check whether a timeseries id exists in the database for a given set of meta data, since it's easy to generate hash and then look for that id in run table rather than mapping each meta data to each field as it would result in several join operations.

[`def is_id_exists(self, id_):`
](https://github.com/shadhini/curw_db_adapter/blob/367b6d8742fbc6902ee9bcab50946ede212c4ad2/db_adapter/curw_fcst/timeseries/timeseries.py#L77)

This method is used to check whether a given id exists in the database.

To generate event id if not exists, [is_id_exists(id_)](https://github.com/shadhini/curw_db_adapter/blob/367b6d8742fbc6902ee9bcab50946ede212c4ad2/db_adapter/curw_fcst/timeseries/timeseries.py#L77) method can be used together with [generate_timeseries_id(meta_data)](https://github.com/shadhini/curw_db_adapter/blob/367b6d8742fbc6902ee9bcab50946ede212c4ad2/db_adapter/curw_fcst/timeseries/timeseries.py#L24), if the id is already known.
